* Author: Vaibhav Kurhe
* Date: 04 Feb 2016

* Environment
  - OS:CentOS-6 
  - Browsers:firefox,Chrome
  - Bandwidth: 100 mbps
  - Hardware Configuration:4 GB
  - Processor:i5

* Objective
  - To view ,take the Posttest and then Submit the Pretest of “Simulate analog and digital function blocks” experiment
 
* Pre Condition
  - Open the url vlabs.ac.in and vlabs home page will be displayed
  - Click on "COE Pune" and a list of labs will be displayed on the screen
  - Select “Industrial Automation Laboratory”, a home page will be displayed on the screen and click on List of Experiments link, 	where a list of experiments will be displayed on the screen
  - Select “Simulate analog and digital function blocks” experiment.

* Post condition
  - Nil	

* Test Step    
  - Click on the Posttest link
  - View the Posttest page with questions and answers
  - Select the radio buttons and click on submit button.
  - In the Posttest select an option only for one question and then click on Submit button
  - click on submit button without selecting any of the option.


* Expected result     
  - Posttest page should be opened
  - Content should be present with no distortions and Junk’s characters
  - The Result should be displayed with the correct option if the selected option is wrong or an error message should be    displayed to complete the Posttest.
  - Give the respective message to select the radio buttons. 
  - Give the respective message to select the radio button before clicking submit button. 



* Review/comments
